---
##########################
# generic

containerized_deployment: true

osd_objectstore: bluestore
osd_scenario: lvm

generate_fsid: false
fsid: {{cookiecutter.ceph_fsid}}

##########################
# network

public_network: {{cookiecutter.ceph_network_frontend}}
cluster_network: {{cookiecutter.ceph_network_backend}}

##########################
# pools & keys

# NOTE: After the initial deployment of the Ceph Clusters, the following parameter can be
#       set to false. It must only be set to true again when new pools or keys are added.
openstack_config: true

openstack_cinder_backup_pool:
  name: backups
  pg_num: 32
  rule_name: ""
  application: "rbd"
openstack_cinder_pool:
  name: volumes
  pg_num: 32
  rule_name: ""
  application: "rbd"
openstack_glance_pool:
  name: images
  pg_num: 32
  rule_name: ""
  application: "rbd"
openstack_gnocchi_pool:
  name: metrics
  pg_num: 32
  rule_name: ""
  application: "rbd"
openstack_nova_pool:
  name: vms
  pg_num: 32
  rule_name: ""
  application: "rbd"

{% raw -%}
openstack_pools:
  - "{{ openstack_cinder_backup_pool }}"
  - "{{ openstack_cinder_pool }}"
  - "{{ openstack_glance_pool }}"
  - "{{ openstack_gnocchi_pool }}"
  - "{{ openstack_nova_pool }}"
{%- endraw %}

{% raw -%}
openstack_keys:
  - name: client.cinder-backup
    caps:
      mon: "allow r"
      osd: "allow class-read object_prefix rbd_children, allow rwx pool={{ openstack_cinder_backup_pool.name }}"
    mode: "0600"
  - name: client.cinder
    caps:
      mon: "allow r"
      osd: "allow class-read object_prefix rbd_children, allow rwx pool={{ openstack_cinder_pool.name }}, allow rwx pool={{ openstack_nova_pool.name }}, allow rx pool={{ openstack_glance_pool.name }}"  # yamllint disable-line rule:line-length
    mode: "0600"
  - name: client.glance
    caps:
      mon: "allow r"
      osd: "allow class-read object_prefix rbd_children, allow rwx pool={{ openstack_glance_pool.name }}"
    mode: "0600"
  - name: client.gnocchi
    caps:
      mon: "allow r"
      osd: "allow class-read object_prefix rbd_children, allow rwx pool={{ openstack_gnocchi_pool.name }}"
    mode: "0600"
  - name: client.nova
    caps:
      mon: "allow r"
      osd: "allow class-read object_prefix rbd_children, allow rwx pool={{ openstack_glance_pool.name }}, allow rwx pool={{ openstack_nova_pool.name }}, allow rwx pool={{ openstack_cinder_pool.name }}, allow rwx pool={{ openstack_cinder_backup_pool.name }}"  # yamllint disable-line rule:line-length
    mode: "0600"
{%- endraw %}

##########################
# manager

ceph_mgr_modules:
  - balancer
  - dashboard
  - prometheus
  - status

##########################
# custom

ceph_conf_overrides:
  mon:
    mon allow pool delete: true
  osd:
    osd pool default size: 3
