---
dist: bionic
language: python

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

script:
  - yamllint cookiecutter.yml.sample
  - flake8 --max-line-length 150 *.py
  - cookiecutter --no-input .
